Repository Kapson007/iHealth, pull requests merged in 2023-01, with the labels that each got.

#20 Home view
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/components/BloodResult.vue
  src/components/BmiCalculatorComponent.vue
  src/components/ButtonComponent.vue
  src/components/CertificatesVaccinesGroupComponent.vue
  src/components/CertsComponent.vue
  src/components/MetricComponent.vue
  src/components/ModalComponent.vue
  src/components/SidebarComponent.vue
  src/composables/getUserData.js
  src/main.js
  src/router/guards.js
  src/router/index.js
  src/stores/userStore.js
  src/styles/model/_mixins.scss
  src/styles/model/variables.scss
  src/view/HomeView.vue
Labels: frontend UI / UX

#28 Modal actions
  src/App.vue
  src/components/BmiCalculatorComponent.vue
  src/components/SidebarComponent.vue
  src/components/auth/LoginFormComponent.vue
  src/composables/getCollections.js
  src/main.js
  src/router/guards.js
  src/router/index.js
  src/stores/userStore.js
  src/view/HomeView.vue
Labels: frontend UI / UX

#22 MakeAVisit
  src/components/DateComponent.vue
  src/components/ModalComponent.vue
  src/components/SidebarComponent.vue
  src/components/auth/CompleteRegistrationFormComponent.vue
  src/components/auth/LoginFormComponent.vue
  src/components/auth/SignupFormComponent.vue
  src/components/dashboard/BmiCalculatorComponent.vue
  src/components/dashboard/ClockComponent.vue
  src/components/dashboard/MetricComponent.vue
  src/components/dashboard/ModalComponent.vue
  src/components/dashboard/ResourceComponent.vue
  src/components/dashboard/tests/BloodResult.vue
  src/components/dashboard/tests/CertificatesVaccinesGroupComponent.vue
  src/components/dashboard/tests/CertsComponent.vue
  src/components/dashboard/tests/ChooseVisitComponent.vue
  src/components/dashboard/tests/VaccinationComponent.vue
  src/composables/getUserData.js
  src/composables/useCollections.js
  src/router/guards.js
  src/router/index.js
  src/stores/userStore.js
  src/utils/allowedTypes.js
  src/utils/dateOption.js
  src/utils/openNewWindow.js
  src/utils/typeOfDocuments.js
  src/utils/typeOfResources.js
  src/view/HomeView.vue
Labels: frontend UI / UX

#38 Fix signup
  src/components/dashboard/tests/BloodResult.vue
  src/components/dashboard/tests/CertificatesVaccinesGroupComponent.vue
  src/router/index.js
  src/view/HomeView.vue
Labels: frontend UI / UX

#39 User issues component
  src/App.vue
  src/components/ButtonComponent.vue
  src/components/DateComponent.vue
  src/components/GreetingsComponent.vue
  src/components/ModalComponent.vue
  src/components/SidebarComponent.vue
  src/components/profile/userInfo/InfoContactComponent.vue
  src/components/profile/userInfo/InfoHandlerComponent.vue
  src/components/profile/userInfo/UserInfoBoxComponent.vue
  src/components/profile/userInfo/UserInfoContainerComponent.vue
  src/components/profile/userInfo/UserInfoLabelComponent.vue
  src/components/profile/userInfo/UserIssueIconComponent.vue
  src/components/profile/userSidebar/UserAvatarComponent.vue
  src/components/profile/userSidebar/UserInfoListComponent.vue
  src/components/profile/userSidebar/UserLabelComponent.vue
  src/components/profile/userSidebar/UserSidebarComponent.vue
  src/main.js
  src/router/guards.js
  src/router/index.js
  src/styles/model/_mixins.scss
  src/styles/model/variables.scss
  src/utils/openNewWindow.js
  src/utils/userIssues.js
  src/view/HomeView.vue
  src/view/ProfileView.vue
Labels: frontend UI / UX

#41 User issues form component
  src/components/ModalComponent.vue
  src/components/dashboard/ResourceComponent.vue
  src/components/dashboard/tests/VaccinationComponent.vue
  src/components/profile/userInfo/InfoHandlerComponent.vue
  src/components/profile/userInfo/UserInfoBoxComponent.vue
  src/components/profile/userInfo/UserInfoContainerComponent.vue
  src/components/profile/userInfo/UserInfoLabelComponent.vue
  src/components/profile/userInfo/UserIssuesFormComponent.vue
  src/router/guards.js
  src/router/index.js
  src/stores/userStore.js
  src/utils/userIssues.js
  src/view/HomeView.vue
  src/view/ProfileView.vue
Labels: frontend UI / UX

#43 Update document hook
  package-lock.json
  package.json
  src/components/dashboard/ClockComponent.vue
  src/components/profile/userInfo/InfoHandlerComponent.vue
  src/components/profile/userInfo/UserInfoLabelComponent.vue
  src/components/profile/userInfo/UserIssuesFormComponent.vue
  src/composables/updateDocument.js
  src/router/index.js
  src/utils/userIssues.js
  src/view/ProfileView.vue
Labels: frontend UI / UX

#45 Close-Contact-Component
  src/components/auth/CompleteRegistrationFormComponent.vue
  src/components/auth/LoginFormComponent.vue
  src/components/dashboard/ResourceComponent.vue
  src/components/dashboard/tests/CertificatesVaccinesGroupComponent.vue
  src/components/profile/userInfo/ContactAvatarComponent.vue
  src/components/profile/userInfo/InfoContactComponent.vue
  src/components/profile/userInfo/InfoHandlerComponent.vue
  src/components/profile/userInfo/RelationTagPillComponent.vue
  src/components/profile/userInfo/UserContactFormComponent.vue
  src/components/profile/userInfo/UserInfoBoxComponent.vue
  src/components/profile/userInfo/UserInfoContainerComponent.vue
  src/composables/sendDefaultUserIssues.js
  src/composables/useSignup.js
  src/main.js
  src/router/index.js
  src/stores/userStore.js
  src/utils/relationship.js
  src/view/ProfileView.vue
Labels: frontend UI / UX

#49 test branch to see where this will going AGAIN
  src/components/referrals/ImportReferralsComponent.vue
  src/components/referrals/ReferralsComponent.vue
  src/stores/userStore.js
  src/utils/medicExamArray.js
  src/utils/specializationArray.js
  src/view/ReferralsView.vue
Labels: backend

#48 CalendarWidget
  index.html
  package-lock.json
  package.json
  src/components/prescriptions/PrescriptionImport.vue
  src/components/profile/userInfo/UserIssuesFormComponent.vue
  src/components/profile/userSidebar/UserSidebarComponent.vue
  src/components/visits/AddVisitFormComponent.vue
  src/components/visits/CalendarNoteComponent.vue
  src/components/visits/VisitsCalendarComponent.vue
  src/components/visits/VisitsDetailsComponent.vue
  src/main.js
  src/stores/userStore.js
  src/utils/userIssues.js
  src/view/PrescriptionView.vue
  src/view/ProfileView.vue
  src/view/VisitsView.vue
Labels: frontend UI / UX

#52 A11y fixes - auth views
  src/components/BrandHeaderComponent.vue
  src/components/ButtonComponent.vue
  src/components/FeatureDescription.vue
  src/components/WelcomeInfoComponent.vue
  src/components/auth/LoginFormComponent.vue
  src/components/auth/SignupFormComponent.vue
  src/view/auth/SignUpView.vue
Labels: enhancement

#55 Accessibility improvements
  src/components/DateComponent.vue
  src/components/ModalComponent.vue
  src/components/dashboard/MetricComponent.vue
  src/components/dashboard/tests/BloodResult.vue
  src/components/dashboard/tests/CertificatesVaccinesGroupComponent.vue
  src/components/dashboard/tests/CertsComponent.vue
  src/components/profile/userSidebar/UserSidebarComponent.vue
  src/components/visits/CalendarNoteComponent.vue
  src/utils/typeOfResources.js
  src/view/ProfileView.vue
  src/view/VisitsView.vue
Labels: enhancement

#57 Accessibility improvements--media
  src/components/ButtonComponent.vue
  src/components/WelcomeInfoComponent.vue
  src/components/auth/CompleteRegistrationFormComponent.vue
  src/components/auth/LoginFormComponent.vue
  src/components/dashboard/tests/CertificatesVaccinesGroupComponent.vue
  src/styles/model/_mixins.scss
  src/styles/model/variables.scss
  src/view/auth/LoginView.vue
  src/view/auth/SignUpView.vue
Labels: frontend UI / UX

#58 Accessibility improvements
  src/components/ButtonComponent.vue
  src/components/DateComponent.vue
  src/components/SidebarComponent.vue
  src/components/dashboard/BmiCalculatorComponent.vue
  src/components/dashboard/ClockComponent.vue
  src/components/dashboard/tests/CertificatesVaccinesGroupComponent.vue
  src/styles/model/variables.scss
  src/view/HomeView.vue
Labels: enhancement, frontend UI / UX
